### ISSUE TITLE
Create June Conf page

### ISSUE THREAD

**Issue by icepcp** [buildingblocs/site#28]
To create a June Conference page in markdown.
- You may refer to this guide for creating a markdown page for events: https://github.com/buildingblocs/site/wiki/Markdown-Pages#creating-an-event-page
- Take a look at https://discordapp.com/channels/698829087354912809/1041316986937946232/1234121598760386570 for the schedule
- Images are not required to be put for now, you may put placeholders
- Don't put workshop details yet

Please get it done by Thursday.

**Comment by Giganaer** [comment]
For "What if something pops up and I can't make it" instruct them to indicate they are not coming via the lu.ma interface. 

For "What are the prizes" please remove "during" in "Given out during after the finals".

For Hackathon Grouping FAQ please remove the school consideration as Mr. Gi does not want this event to be a school vs school competition

**Comment by Walnit** [comment]
Alright, should be fixed in the latest commit. Apologies for the minor mistakes.
